package org.manufacturingoot.view;

import java.util.Date;
import java.util.List;
import javax.persistence.EntityManagerFactory;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import org.manufacturingoot.model.BillOfMaterial;
import org.manufacturingoot.model.Part;
import org.manufacturingoot.model.Product;
import org.manufacturingoot.service.BillOfMaterialService;
import org.manufacturingoot.service.PartService;
import org.manufacturingoot.service.ProductService;

public class ChoosePartPanel extends javax.swing.JFrame {

    private EntityManagerFactory emf;
    private Product product;
    BillOfMaterialService boms;

    /**
     * Creates new form ChoosePartPanel
     */
    public ChoosePartPanel(EntityManagerFactory emf, Product product) {
        initComponents();
        this.emf = emf;
        this.product = product == null ? new Product() : product;
        this.boms = new BillOfMaterialService(emf);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        loadTable();
    }

    private void loadTable() {
        PartService ps = new PartService(emf);
        List<Part> rows = ps.findPartEntities();

        DefaultTableModel model = (DefaultTableModel) tableData.getModel();

        for (Part current : rows) {
            BillOfMaterial temp = boms.findBillOfMaterialByFK(current, product);
            Object[] data = {
                current.getId(),
                current.getName(),
                current.getStock(),
                temp.getAmount()
            };
            model.addRow(data);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableData = new javax.swing.JTable();
        buttonSave = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Choose Parts");

        tableData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Stock", "Needed"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableData);

        buttonSave.setText("Save");
        buttonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonSave)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonSave)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSaveActionPerformed
        // TODO add your handling code here:
        PartService ps = new PartService(emf);
        ProductService productService = new ProductService(emf);

        DefaultTableModel tableModel = (DefaultTableModel) tableData.getModel();
        for (int i = 0; i < tableModel.getRowCount(); i++) {
            int total = Integer.parseInt(tableModel.getValueAt(i, 3).toString());
            if (total > 0) {
                try {
                    long id = Long.parseLong(tableModel.getValueAt(i, 0).toString());
                    Part part = ps.findPart(id);
                    part.setStock(part.getStock() - (total - part.getStock()));
                    ps.edit(part);

                    BillOfMaterial bom = boms.findBillOfMaterialByFK(part, product);
                    bom.setRequestDate(new Date());
                    bom.setAmount(total);
                    bom.setPart(part);
                    bom.setProduct(product);
                    boms.edit(bom);

                    // update belum
                    product.calculateCost();
                    productService.edit(product);
                } catch (Exception ex) {
                    ex.printStackTrace();
                }
            }
        }
    }//GEN-LAST:event_buttonSaveActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableData;
    // End of variables declaration//GEN-END:variables
}
